"use client";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppSidebar } from "@/components/app-sidebar";
import { AvatarImage, Avatar } from "@/components/ui/avatar";
import {
  Breadcrumb,
  BreadcrumbList,
  BreadcrumbItem,
} from "@/components/ui/breadcrumb";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { BrainIcon } from "lucide-react";

import { useViewStore } from "../store/view-store";

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const activeView = useViewStore((state) => state.activeView);
  const activeStudent = useViewStore((state) => state.activeStudent);
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <SidebarProvider>
          <AppSidebar />
          <SidebarTrigger />

          {
            <main className="flex w-full h-screen justify-center items-start">
              {activeView === "discussion" ? (
                children
              ) : (
                <div className="flex flex-col w-full h-full">
                  <div className="flex flex-col items-center justify-center p-4 bg-background sticky top-0 z-10">
                    <Breadcrumb>
                      <BreadcrumbList>
                        <BreadcrumbItem>
                          <div className="flex justify-center items-center">
                            <Avatar>
                              <AvatarImage
                                src={
                                  activeStudent?.avatar ||
                                  "/images/default-avatar.png"
                                }
                                className="rounded-full mr-2"
                                height={"32px"}
                                width={"32px"}
                              />
                            </Avatar>
                            <span>
                              {activeStudent?.name || "Select a student"}
                            </span>
                          </div>
                        </BreadcrumbItem>
                      </BreadcrumbList>
                    </Breadcrumb>
                  </div>
                  <div className="flex-1 overflow-y-auto [&::-webkit-scrollbar]:hidden [-ms-overflow-style:'none'] [scrollbar-width:'none']">
                    <div className="flex h-full flex-col justify-center items-center gap-4">
                      <div className="flex items-center justify-center w-20 h-20 rounded-full bg-primary/10">
                        <BrainIcon className="w-10 h-10 text-primary" />
                      </div>
                      <div className="flex flex-col items-center gap-2">
                        <span className="text-xl font-semibold text-primary">
                          Digital Twin
                        </span>
                        <span className="text-sm text-muted-foreground">
                          Start a conversation with{" "}
                          {activeStudent?.name || "your"}
                          {"'s "}
                          digital twin
                        </span>
                      </div>
                    </div>
                  </div>
                  <div className="sticky bottom-0 flex justify-center w-full bg-background p-4">
                    {/* <Prompter /> */}
                  </div>
                </div>
              )}
            </main>
          }

          {/* <DropdownMenuDemo /> */}
        </SidebarProvider>
      </body>
    </html>
  );
}
